version: "3"
services:
  mysql:
    image: "mysql"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "node_app"
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
  web:
    depends_on:
      - mysql
    restart: on-failure
    build: .
    ports:
      - "3000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
      MYSQL_DATABASE: "node_app"
